[project]
name = "drawapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ogd1295a-byte", email = "ogd1295a@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.62.0",
]

[project.scripts]
drawapp = "drawapp:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
